# sonarqube-optimized.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata
